name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install --upgrade Flask Werkzeug

    - name: Run tests
      run: |
        python -m pytest
    - name: Deploy to Azure VM
      if: success()
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SSH_PUBLIC_KEY: ${{ secrets.SSH_PUBLIC_KEY }}
      run: |
        echo "$SSH_PRIVATE_KEY" > ssh_private_key
        chmod 600 ssh_private_key
        touch ~/.ssh/known_hosts
        ssh-keyscan -H 52.172.221.49 >> ~/.ssh/known_hosts
        ssh -i ssh_private_key azureuser@52.172.221.49 "cd /home/azureuser/helloworld/ && git pull origin main && pip install -r requirements.txt && python3 task1.py"

        rm ssh_private_key

